import random

def encryptOTP(text_file):

     # this function encrypts a message using a 
     # one time pad and outputs the encrypted
     # message and a key to decrypt the message

     text_list = []
     ascii_list = []
     binary_list = []
     key = []
     total_length = 0
     truekey = 0
     mesage = 0
     encrypted_list =[]

     file_object = open(text_file, 'r')
     text =  file_object.read()
     text_list.append(text)

     for words in text_list:
          for letters in words:
               ascii_list.append(ord(letters))

     for integers in ascii_list:
         binary_list . append('{0:08b}'.format(integers))

     message = ''.join(binary_list)
     
     for items in binary_list:
          total_length += len(items)
          

     for x in range( 0, total_length / 8):
          key.append('{0:08b}'.format(random.randint(0,255)))
     truekey = ''.join(key)
     key_file = open("key.txt", "w")
     key_file.write(truekey)
     key_file.close()

     for x in range(0,len(message)):

          if message[x] == '0' and truekey[x]== '0':
               encrypted_list.append('0')
          elif message[x] == '0' and truekey[x] == '1':
               encrypted_list.append('1')
          elif message[x] == '1' and truekey[x]== '0':
               encrypted_list.append('1')
          elif message[x] == '1' and truekey[x] == '1':
               encrypted_list.append('0')
     
     encryption = ''.join(encrypted_list)
     message_file = open("message.txt", "w")
     message_file.write(encryption)
     message_file.close()


def decrypt(message_text, key_text):

     # this function decrypts the encrypted
     # message using the encrypted text and
     # the key that was generated by the encryptOTP
     # function 
     
     decrypted_list = []
     binary_list = []
     ascii_list =[]
     dec_message = ''
     key_object = open(key_text, 'r')
     key = key_object.read()
     key = str(key)
     message_object = open(message_text, 'r')
     message = message_object.read()

     length = len(key)
     for x in range(0,length):

          if message[x] == '0' and key[x]== '0':
               decrypted_list.append('0')
          elif message[x] == '0' and key[x] == '1':
               decrypted_list.append('1')
          elif message[x] == '1' and key[x]== '0':
               decrypted_list.append('1')
          elif message[x] == '1' and key[x] == '1':
               decrypted_list.append('0')
     
     binary_number = ''.join(decrypted_list)
     while len(binary_number) > 0 :
          binary_number1 = binary_number[0:8]
          binary_number = binary_number[8:]
          binary_list.append(binary_number1)
     for numbers in binary_list:
          ascii_value = int(numbers, 2)
          ascii_list.append(ascii_value)


     dec_message = ''.join(chr(i) for i in ascii_list)
     
     message_file = open("dec_message.txt","w")
     message_file.write(dec_message)
     message_file.close
     
